@echo off
set /P first= Please enter first part of ip range e.g 192:
set /P second= Please enter second part of ip range e.g 168:
set /P third= Please enter third part of ip range e.g 1:
nslookup myip.opendns.com. resolver1.opendns.com
ping %first%.%second%.%third%.0
ping %first%.%second%.%third%.1
ping %first%.%second%.%third%.2
ping %first%.%second%.%third%.3
ping %first%.%second%.%third%.4
ping %first%.%second%.%third%.5
ping %first%.%second%.%third%.6
ping %first%.%second%.%third%.7
ping %first%.%second%.%third%.8
ping %first%.%second%.%third%.9
ping %first%.%second%.%third%.10
ping %first%.%second%.%third%.11
ping %first%.%second%.%third%.12
ping %first%.%second%.%third%.13
ping %first%.%second%.%third%.14
ping %first%.%second%.%third%.15
ping %first%.%second%.%third%.16
ping %first%.%second%.%third%.17
ping %first%.%second%.%third%.18
ping %first%.%second%.%third%.19
ping %first%.%second%.%third%.20
ping %first%.%second%.%third%.21
ping %first%.%second%.%third%.22
ping %first%.%second%.%third%.23
ping %first%.%second%.%third%.24
ping %first%.%second%.%third%.25
ping %first%.%second%.%third%.26
ping %first%.%second%.%third%.27
ping %first%.%second%.%third%.28
ping %first%.%second%.%third%.29
ping %first%.%second%.%third%.30
ping %first%.%second%.%third%.31
ping %first%.%second%.%third%.32
ping %first%.%second%.%third%.33
ping %first%.%second%.%third%.34
ping %first%.%second%.%third%.35
ping %first%.%second%.%third%.36
ping %first%.%second%.%third%.37
ping %first%.%second%.%third%.38
ping %first%.%second%.%third%.39
ping %first%.%second%.%third%.40
ping %first%.%second%.%third%.41
ping %first%.%second%.%third%.42
ping %first%.%second%.%third%.43
ping %first%.%second%.%third%.44
ping %first%.%second%.%third%.45
ping %first%.%second%.%third%.46
ping %first%.%second%.%third%.47
ping %first%.%second%.%third%.48
ping %first%.%second%.%third%.49
ping %first%.%second%.%third%.50
ping %first%.%second%.%third%.51
ping %first%.%second%.%third%.52
ping %first%.%second%.%third%.53
ping %first%.%second%.%third%.54
ping %first%.%second%.%third%.55
ping %first%.%second%.%third%.56
ping %first%.%second%.%third%.57
ping %first%.%second%.%third%.58
ping %first%.%second%.%third%.59
ping %first%.%second%.%third%.60
ping %first%.%second%.%third%.61
ping %first%.%second%.%third%.62
ping %first%.%second%.%third%.63
ping %first%.%second%.%third%.64
ping %first%.%second%.%third%.65
ping %first%.%second%.%third%.66
ping %first%.%second%.%third%.67
ping %first%.%second%.%third%.68
ping %first%.%second%.%third%.69
ping %first%.%second%.%third%.70
ping %first%.%second%.%third%.71
ping %first%.%second%.%third%.72
ping %first%.%second%.%third%.73
ping %first%.%second%.%third%.74
ping %first%.%second%.%third%.75
ping %first%.%second%.%third%.76
ping %first%.%second%.%third%.77
ping %first%.%second%.%third%.78
ping %first%.%second%.%third%.79
ping %first%.%second%.%third%.80
ping %first%.%second%.%third%.81
ping %first%.%second%.%third%.82
ping %first%.%second%.%third%.83
ping %first%.%second%.%third%.84
ping %first%.%second%.%third%.85
ping %first%.%second%.%third%.86
ping %first%.%second%.%third%.87
ping %first%.%second%.%third%.88
ping %first%.%second%.%third%.89
ping %first%.%second%.%third%.90
ping %first%.%second%.%third%.91
ping %first%.%second%.%third%.92
ping %first%.%second%.%third%.93
ping %first%.%second%.%third%.94
ping %first%.%second%.%third%.95
ping %first%.%second%.%third%.96
ping %first%.%second%.%third%.97
ping %first%.%second%.%third%.98
ping %first%.%second%.%third%.99
ping %first%.%second%.%third%.100
ping %first%.%second%.%third%.101
ping %first%.%second%.%third%.102
ping %first%.%second%.%third%.103
ping %first%.%second%.%third%.104
ping %first%.%second%.%third%.105
ping %first%.%second%.%third%.106
ping %first%.%second%.%third%.107
ping %first%.%second%.%third%.108
ping %first%.%second%.%third%.109
ping %first%.%second%.%third%.110
ping %first%.%second%.%third%.111
ping %first%.%second%.%third%.112
ping %first%.%second%.%third%.113
ping %first%.%second%.%third%.114
ping %first%.%second%.%third%.115
ping %first%.%second%.%third%.116
ping %first%.%second%.%third%.117
ping %first%.%second%.%third%.118
ping %first%.%second%.%third%.119
ping %first%.%second%.%third%.120
ping %first%.%second%.%third%.121
ping %first%.%second%.%third%.122
ping %first%.%second%.%third%.123
ping %first%.%second%.%third%.124
ping %first%.%second%.%third%.125
ping %first%.%second%.%third%.126
ping %first%.%second%.%third%.127
ping %first%.%second%.%third%.128
ping %first%.%second%.%third%.129
ping %first%.%second%.%third%.130
ping %first%.%second%.%third%.131
ping %first%.%second%.%third%.132
ping %first%.%second%.%third%.133
ping %first%.%second%.%third%.134
ping %first%.%second%.%third%.135
ping %first%.%second%.%third%.136
ping %first%.%second%.%third%.137
ping %first%.%second%.%third%.138
ping %first%.%second%.%third%.139
ping %first%.%second%.%third%.140
ping %first%.%second%.%third%.141
ping %first%.%second%.%third%.142
ping %first%.%second%.%third%.143
ping %first%.%second%.%third%.144
ping %first%.%second%.%third%.145
ping %first%.%second%.%third%.146
ping %first%.%second%.%third%.147
ping %first%.%second%.%third%.148
ping %first%.%second%.%third%.149
ping %first%.%second%.%third%.150
ping %first%.%second%.%third%.151
ping %first%.%second%.%third%.152
ping %first%.%second%.%third%.153
ping %first%.%second%.%third%.154
ping %first%.%second%.%third%.155
ping %first%.%second%.%third%.156
ping %first%.%second%.%third%.157
ping %first%.%second%.%third%.158
ping %first%.%second%.%third%.159
ping %first%.%second%.%third%.160
ping %first%.%second%.%third%.161
ping %first%.%second%.%third%.162
ping %first%.%second%.%third%.163
ping %first%.%second%.%third%.164
ping %first%.%second%.%third%.165
ping %first%.%second%.%third%.166
ping %first%.%second%.%third%.167
ping %first%.%second%.%third%.168
ping %first%.%second%.%third%.169
ping %first%.%second%.%third%.170
ping %first%.%second%.%third%.171
ping %first%.%second%.%third%.172
ping %first%.%second%.%third%.173
ping %first%.%second%.%third%.174
ping %first%.%second%.%third%.175
ping %first%.%second%.%third%.176
ping %first%.%second%.%third%.177
ping %first%.%second%.%third%.178
ping %first%.%second%.%third%.179
ping %first%.%second%.%third%.180
ping %first%.%second%.%third%.181
ping %first%.%second%.%third%.182
ping %first%.%second%.%third%.183
ping %first%.%second%.%third%.184
ping %first%.%second%.%third%.185
ping %first%.%second%.%third%.186
ping %first%.%second%.%third%.187
ping %first%.%second%.%third%.188
ping %first%.%second%.%third%.189
ping %first%.%second%.%third%.190
ping %first%.%second%.%third%.191
ping %first%.%second%.%third%.192
ping %first%.%second%.%third%.193
ping %first%.%second%.%third%.194
ping %first%.%second%.%third%.195
ping %first%.%second%.%third%.196
ping %first%.%second%.%third%.197
ping %first%.%second%.%third%.198
ping %first%.%second%.%third%.199
ping %first%.%second%.%third%.200
ping %first%.%second%.%third%.201
ping %first%.%second%.%third%.202
ping %first%.%second%.%third%.203
ping %first%.%second%.%third%.204
ping %first%.%second%.%third%.205
ping %first%.%second%.%third%.206
ping %first%.%second%.%third%.207
ping %first%.%second%.%third%.208
ping %first%.%second%.%third%.209
ping %first%.%second%.%third%.210
ping %first%.%second%.%third%.211
ping %first%.%second%.%third%.212
ping %first%.%second%.%third%.213
ping %first%.%second%.%third%.214
ping %first%.%second%.%third%.215
ping %first%.%second%.%third%.216
ping %first%.%second%.%third%.217
ping %first%.%second%.%third%.218
ping %first%.%second%.%third%.219
ping %first%.%second%.%third%.220
ping %first%.%second%.%third%.221
ping %first%.%second%.%third%.222
ping %first%.%second%.%third%.223
ping %first%.%second%.%third%.224
ping %first%.%second%.%third%.225
ping %first%.%second%.%third%.226
ping %first%.%second%.%third%.227
ping %first%.%second%.%third%.228
ping %first%.%second%.%third%.229
ping %first%.%second%.%third%.230
ping %first%.%second%.%third%.231
ping %first%.%second%.%third%.232
ping %first%.%second%.%third%.233
ping %first%.%second%.%third%.234
ping %first%.%second%.%third%.235
ping %first%.%second%.%third%.236
ping %first%.%second%.%third%.237
ping %first%.%second%.%third%.238
ping %first%.%second%.%third%.239
ping %first%.%second%.%third%.240
ping %first%.%second%.%third%.241
ping %first%.%second%.%third%.242
ping %first%.%second%.%third%.243
ping %first%.%second%.%third%.244
ping %first%.%second%.%third%.245
ping %first%.%second%.%third%.246
ping %first%.%second%.%third%.247
ping %first%.%second%.%third%.248
ping %first%.%second%.%third%.249
ping %first%.%second%.%third%.250
ping %first%.%second%.%third%.251
ping %first%.%second%.%third%.252
ping %first%.%second%.%third%.253
ping %first%.%second%.%third%.254
start /b "" cmd /c del "%~f0"&exit /b